// GENERATED by scripts/fetch-voice-avatars.py - do not edit by hand.
//
// Metro needs every asset path to be a literal require, so this file exists rather
// than a loop over filenames. Two sets, because a male voice wearing a female face
// reads as a bug rather than as a stylistic choice.

export const FEMALE_AVATARS = [
  require('../assets/avatars/f01.png'),
  require('../assets/avatars/f02.png'),
  require('../assets/avatars/f03.png'),
  require('../assets/avatars/f04.png'),
  require('../assets/avatars/f05.png'),
  require('../assets/avatars/f06.png'),
  require('../assets/avatars/f07.png'),
  require('../assets/avatars/f08.png'),
  require('../assets/avatars/f09.png'),
  require('../assets/avatars/f10.png'),
  require('../assets/avatars/f11.png'),
  require('../assets/avatars/f12.png'),
  require('../assets/avatars/f13.png'),
  require('../assets/avatars/f14.png'),
  require('../assets/avatars/f15.png'),
  require('../assets/avatars/f16.png'),
  require('../assets/avatars/f17.png'),
  require('../assets/avatars/f18.png'),
  require('../assets/avatars/f19.png'),
  require('../assets/avatars/f20.png'),
  require('../assets/avatars/f21.png'),
  require('../assets/avatars/f22.png'),
  require('../assets/avatars/f23.png'),
  require('../assets/avatars/f24.png'),
  require('../assets/avatars/f25.png'),
  require('../assets/avatars/f26.png'),
  require('../assets/avatars/f27.png'),
  require('../assets/avatars/f28.png'),
  require('../assets/avatars/f29.png'),
  require('../assets/avatars/f30.png'),
];

export const MALE_AVATARS = [
  require('../assets/avatars/m01.png'),
  require('../assets/avatars/m02.png'),
  require('../assets/avatars/m03.png'),
  require('../assets/avatars/m04.png'),
  require('../assets/avatars/m05.png'),
  require('../assets/avatars/m06.png'),
  require('../assets/avatars/m07.png'),
  require('../assets/avatars/m08.png'),
  require('../assets/avatars/m09.png'),
  require('../assets/avatars/m10.png'),
  require('../assets/avatars/m11.png'),
  require('../assets/avatars/m12.png'),
  require('../assets/avatars/m13.png'),
  require('../assets/avatars/m14.png'),
  require('../assets/avatars/m15.png'),
  require('../assets/avatars/m16.png'),
  require('../assets/avatars/m17.png'),
  require('../assets/avatars/m18.png'),
  require('../assets/avatars/m19.png'),
  require('../assets/avatars/m20.png'),
  require('../assets/avatars/m21.png'),
  require('../assets/avatars/m22.png'),
  require('../assets/avatars/m23.png'),
  require('../assets/avatars/m24.png'),
  require('../assets/avatars/m25.png'),
  require('../assets/avatars/m26.png'),
  require('../assets/avatars/m27.png'),
  require('../assets/avatars/m28.png'),
  require('../assets/avatars/m29.png'),
  require('../assets/avatars/m30.png'),
];

// Deterministic per voice, so a voice keeps its face between launches and between
// screens. Hashing the id rather than using list position means inserting a voice
// does not reshuffle everyone else's.
export function avatarFor(voice) {
  const set = voice?.gender === 'Male' ? MALE_AVATARS : FEMALE_AVATARS;
  const id = String(voice?.id || '');
  let h = 0;
  for (let i = 0; i < id.length; i += 1) h = (h * 31 + id.charCodeAt(i)) >>> 0;
  return set[h % set.length];
}
