// GENERATED by scripts/gen-recipe-previews.mjs - do not edit by hand.
// Bumped whenever the tiles are re-rendered, so a cached one is not served forever.
export const EFFECT_PREVIEW_VERSION = 1787227735988;
