// GENERATED - do not edit by hand.
// Regenerate with scripts/fetch-fonts.py (families in scripts/fonts.families.txt),
// then copy the TTFs into assets/fonts and the backend's fonts directory. The
// backend renders the export from files of the same name, so a family added on
// one side and not the other previews in one font and exports in another.
//
// Metro needs a literal path in every require, which is why this file is a table
// of them rather than a loop over the manifest.

export const FONT_ASSETS = {
  'Assistant': require('../assets/fonts/Assistant-Bold.ttf'),
  'Barlow': require('../assets/fonts/Barlow-Bold.ttf'),
  'Cabin': require('../assets/fonts/Cabin-Bold.ttf'),
  'Chivo': require('../assets/fonts/Chivo-Bold.ttf'),
  'DM Sans': require('../assets/fonts/DMSans-Bold.ttf'),
  'Exo 2': require('../assets/fonts/Exo2-Bold.ttf'),
  'Figtree': require('../assets/fonts/Figtree-Bold.ttf'),
  'Fredoka': require('../assets/fonts/Fredoka-Bold.ttf'),
  'Heebo': require('../assets/fonts/Heebo-Bold.ttf'),
  'Inter': require('../assets/fonts/Inter-Bold.ttf'),
  'Josefin Sans': require('../assets/fonts/JosefinSans-Bold.ttf'),
  'Kanit': require('../assets/fonts/Kanit-Bold.ttf'),
  'Karla': require('../assets/fonts/Karla-Bold.ttf'),
  'Lato': require('../assets/fonts/Lato-Bold.ttf'),
  'Manrope': require('../assets/fonts/Manrope-Bold.ttf'),
  'Montserrat': require('../assets/fonts/Montserrat-Bold.ttf'),
  'Mulish': require('../assets/fonts/Mulish-Bold.ttf'),
  'Nunito': require('../assets/fonts/Nunito-Bold.ttf'),
  'Nunito Sans': require('../assets/fonts/NunitoSans-Bold.ttf'),
  'Open Sans': require('../assets/fonts/OpenSans-Bold.ttf'),
  'Oswald': require('../assets/fonts/Oswald-Bold.ttf'),
  'Outfit': require('../assets/fonts/Outfit-Bold.ttf'),
  'Overpass': require('../assets/fonts/Overpass-Bold.ttf'),
  'Plus Jakarta Sans': require('../assets/fonts/PlusJakartaSans-Bold.ttf'),
  'Poppins': require('../assets/fonts/Poppins-Bold.ttf'),
  'Public Sans': require('../assets/fonts/PublicSans-Bold.ttf'),
  'Quicksand': require('../assets/fonts/Quicksand-Bold.ttf'),
  'Raleway': require('../assets/fonts/Raleway-Bold.ttf'),
  'Roboto': require('../assets/fonts/Roboto-Bold.ttf'),
  'Rubik': require('../assets/fonts/Rubik-Bold.ttf'),
  'Sora': require('../assets/fonts/Sora-Bold.ttf'),
  'Titillium Web': require('../assets/fonts/TitilliumWeb-Bold.ttf'),
  'Urbanist': require('../assets/fonts/Urbanist-Bold.ttf'),
  'Work Sans': require('../assets/fonts/WorkSans-Bold.ttf'),
  'Alfa Slab One': require('../assets/fonts/AlfaSlabOne-Regular.ttf'),
  'Anton': require('../assets/fonts/Anton-Regular.ttf'),
  'Archivo Black': require('../assets/fonts/ArchivoBlack-Regular.ttf'),
  'Audiowide': require('../assets/fonts/Audiowide-Regular.ttf'),
  'Baloo 2': require('../assets/fonts/Baloo2-Bold.ttf'),
  'Bangers': require('../assets/fonts/Bangers-Regular.ttf'),
  'Bebas Neue': require('../assets/fonts/BebasNeue-Regular.ttf'),
  'Bevan': require('../assets/fonts/Bevan-Regular.ttf'),
  'Black Ops One': require('../assets/fonts/BlackOpsOne-Regular.ttf'),
  'Bungee': require('../assets/fonts/Bungee-Regular.ttf'),
  'Bungee Inline': require('../assets/fonts/BungeeInline-Regular.ttf'),
  'Bungee Shade': require('../assets/fonts/BungeeShade-Regular.ttf'),
  'Carter One': require('../assets/fonts/CarterOne-Regular.ttf'),
  'Chewy': require('../assets/fonts/Chewy-Regular.ttf'),
  'Creepster': require('../assets/fonts/Creepster-Regular.ttf'),
  'Days One': require('../assets/fonts/DaysOne-Regular.ttf'),
  'Faster One': require('../assets/fonts/FasterOne-Regular.ttf'),
  'Frijole': require('../assets/fonts/Frijole-Regular.ttf'),
  'Fugaz One': require('../assets/fonts/FugazOne-Regular.ttf'),
  'Gravitas One': require('../assets/fonts/GravitasOne-Regular.ttf'),
  'Lilita One': require('../assets/fonts/LilitaOne-Regular.ttf'),
  'Luckiest Guy': require('../assets/fonts/LuckiestGuy-Regular.ttf'),
  'Michroma': require('../assets/fonts/Michroma-Regular.ttf'),
  'Monoton': require('../assets/fonts/Monoton-Regular.ttf'),
  'Nosifer': require('../assets/fonts/Nosifer-Regular.ttf'),
  'Orbitron': require('../assets/fonts/Orbitron-Bold.ttf'),
  'Passion One': require('../assets/fonts/PassionOne-Bold.ttf'),
  'Press Start 2P': require('../assets/fonts/PressStart2P-Regular.ttf'),
  'Rampart One': require('../assets/fonts/RampartOne-Regular.ttf'),
  'Righteous': require('../assets/fonts/Righteous-Regular.ttf'),
  'Russo One': require('../assets/fonts/RussoOne-Regular.ttf'),
  'Secular One': require('../assets/fonts/SecularOne-Regular.ttf'),
  'Shrikhand': require('../assets/fonts/Shrikhand-Regular.ttf'),
  'Sigmar One': require('../assets/fonts/SigmarOne-Regular.ttf'),
  'Silkscreen': require('../assets/fonts/Silkscreen-Regular.ttf'),
  'Special Elite': require('../assets/fonts/SpecialElite-Regular.ttf'),
  'Squada One': require('../assets/fonts/SquadaOne-Regular.ttf'),
  'Staatliches': require('../assets/fonts/Staatliches-Regular.ttf'),
  'Syncopate': require('../assets/fonts/Syncopate-Bold.ttf'),
  'Teko': require('../assets/fonts/Teko-Bold.ttf'),
  'Titan One': require('../assets/fonts/TitanOne-Regular.ttf'),
  'Ultra': require('../assets/fonts/Ultra-Regular.ttf'),
  'Wallpoet': require('../assets/fonts/Wallpoet-Regular.ttf'),
  'Abril Fatface': require('../assets/fonts/AbrilFatface-Regular.ttf'),
  'Arvo': require('../assets/fonts/Arvo-Bold.ttf'),
  'Bitter': require('../assets/fonts/Bitter-Bold.ttf'),
  'Cardo': require('../assets/fonts/Cardo-Bold.ttf'),
  'Cormorant Garamond': require('../assets/fonts/CormorantGaramond-Bold.ttf'),
  'Crimson Text': require('../assets/fonts/CrimsonText-Bold.ttf'),
  'Domine': require('../assets/fonts/Domine-Bold.ttf'),
  'EB Garamond': require('../assets/fonts/EBGaramond-Bold.ttf'),
  'Libre Baskerville': require('../assets/fonts/LibreBaskerville-Bold.ttf'),
  'Lora': require('../assets/fonts/Lora-Bold.ttf'),
  'Merriweather': require('../assets/fonts/Merriweather-Bold.ttf'),
  'Neuton': require('../assets/fonts/Neuton-Bold.ttf'),
  'Playfair Display': require('../assets/fonts/PlayfairDisplay-Bold.ttf'),
  'Prata': require('../assets/fonts/Prata-Regular.ttf'),
  'Rokkitt': require('../assets/fonts/Rokkitt-Bold.ttf'),
  'Spectral': require('../assets/fonts/Spectral-Bold.ttf'),
  'Vollkorn': require('../assets/fonts/Vollkorn-Bold.ttf'),
  'Yeseva One': require('../assets/fonts/YesevaOne-Regular.ttf'),
  'Zilla Slab': require('../assets/fonts/ZillaSlab-Bold.ttf'),
  'Allura': require('../assets/fonts/Allura-Regular.ttf'),
  'Amatic SC': require('../assets/fonts/AmaticSC-Bold.ttf'),
  'Architects Daughter': require('../assets/fonts/ArchitectsDaughter-Regular.ttf'),
  'Bad Script': require('../assets/fonts/BadScript-Regular.ttf'),
  'Berkshire Swash': require('../assets/fonts/BerkshireSwash-Regular.ttf'),
  'Caveat': require('../assets/fonts/Caveat-Bold.ttf'),
  'Cookie': require('../assets/fonts/Cookie-Regular.ttf'),
  'Courgette': require('../assets/fonts/Courgette-Regular.ttf'),
  'Dancing Script': require('../assets/fonts/DancingScript-Bold.ttf'),
  'Gloria Hallelujah': require('../assets/fonts/GloriaHallelujah-Regular.ttf'),
  'Great Vibes': require('../assets/fonts/GreatVibes-Regular.ttf'),
  'Indie Flower': require('../assets/fonts/IndieFlower-Regular.ttf'),
  'Kaushan Script': require('../assets/fonts/KaushanScript-Regular.ttf'),
  'Lobster': require('../assets/fonts/Lobster-Regular.ttf'),
  'Marck Script': require('../assets/fonts/MarckScript-Regular.ttf'),
  'Pacifico': require('../assets/fonts/Pacifico-Regular.ttf'),
  'Parisienne': require('../assets/fonts/Parisienne-Regular.ttf'),
  'Patrick Hand': require('../assets/fonts/PatrickHand-Regular.ttf'),
  'Permanent Marker': require('../assets/fonts/PermanentMarker-Regular.ttf'),
  'Rock Salt': require('../assets/fonts/RockSalt-Regular.ttf'),
  'Sacramento': require('../assets/fonts/Sacramento-Regular.ttf'),
  'Satisfy': require('../assets/fonts/Satisfy-Regular.ttf'),
  'Shadows Into Light': require('../assets/fonts/ShadowsIntoLight-Regular.ttf'),
  'Yellowtail': require('../assets/fonts/Yellowtail-Regular.ttf'),
  'Cousine': require('../assets/fonts/Cousine-Bold.ttf'),
  'Fira Code': require('../assets/fonts/FiraCode-Bold.ttf'),
  'IBM Plex Mono': require('../assets/fonts/IBMPlexMono-Bold.ttf'),
  'Inconsolata': require('../assets/fonts/Inconsolata-Bold.ttf'),
  'JetBrains Mono': require('../assets/fonts/JetBrainsMono-Bold.ttf'),
  'Roboto Mono': require('../assets/fonts/RobotoMono-Bold.ttf'),
  'Share Tech Mono': require('../assets/fonts/ShareTechMono-Regular.ttf'),
  'Source Code Pro': require('../assets/fonts/SourceCodePro-Bold.ttf'),
  'Space Mono': require('../assets/fonts/SpaceMono-Bold.ttf'),
  'VT323': require('../assets/fonts/VT323-Regular.ttf'),
};

// Grouped for the picker, in the order the sections are shown.
export const FONT_GROUPS = [
  { label: 'Sans', fonts: ['Assistant', 'Barlow', 'Cabin', 'Chivo', 'DM Sans', 'Exo 2', 'Figtree', 'Fredoka', 'Heebo', 'Inter', 'Josefin Sans', 'Kanit', 'Karla', 'Lato', 'Manrope', 'Montserrat', 'Mulish', 'Nunito', 'Nunito Sans', 'Open Sans', 'Oswald', 'Outfit', 'Overpass', 'Plus Jakarta Sans', 'Poppins', 'Public Sans', 'Quicksand', 'Raleway', 'Roboto', 'Rubik', 'Sora', 'Titillium Web', 'Urbanist', 'Work Sans'] },
  { label: 'Display', fonts: ['Alfa Slab One', 'Anton', 'Archivo Black', 'Audiowide', 'Baloo 2', 'Bangers', 'Bebas Neue', 'Bevan', 'Black Ops One', 'Bungee', 'Bungee Inline', 'Bungee Shade', 'Carter One', 'Chewy', 'Creepster', 'Days One', 'Faster One', 'Frijole', 'Fugaz One', 'Gravitas One', 'Lilita One', 'Luckiest Guy', 'Michroma', 'Monoton', 'Nosifer', 'Orbitron', 'Passion One', 'Press Start 2P', 'Rampart One', 'Righteous', 'Russo One', 'Secular One', 'Shrikhand', 'Sigmar One', 'Silkscreen', 'Special Elite', 'Squada One', 'Staatliches', 'Syncopate', 'Teko', 'Titan One', 'Ultra', 'Wallpoet'] },
  { label: 'Serif', fonts: ['Abril Fatface', 'Arvo', 'Bitter', 'Cardo', 'Cormorant Garamond', 'Crimson Text', 'Domine', 'EB Garamond', 'Libre Baskerville', 'Lora', 'Merriweather', 'Neuton', 'Playfair Display', 'Prata', 'Rokkitt', 'Spectral', 'Vollkorn', 'Yeseva One', 'Zilla Slab'] },
  { label: 'Handwriting', fonts: ['Allura', 'Amatic SC', 'Architects Daughter', 'Bad Script', 'Berkshire Swash', 'Caveat', 'Cookie', 'Courgette', 'Dancing Script', 'Gloria Hallelujah', 'Great Vibes', 'Indie Flower', 'Kaushan Script', 'Lobster', 'Marck Script', 'Pacifico', 'Parisienne', 'Patrick Hand', 'Permanent Marker', 'Rock Salt', 'Sacramento', 'Satisfy', 'Shadows Into Light', 'Yellowtail'] },
  { label: 'Mono', fonts: ['Cousine', 'Fira Code', 'IBM Plex Mono', 'Inconsolata', 'JetBrains Mono', 'Roboto Mono', 'Share Tech Mono', 'Source Code Pro', 'Space Mono', 'VT323'] },
];

export const FONT_NAMES = Object.keys(FONT_ASSETS);

// What the picker offered before real families existed. Overlays saved then still
// carry these, and the renderer still reads them as weight and slant on the system
// face, so they must not be treated as a missing family.
export const LEGACY_FONTS = ['Default', 'Bold', 'Italic', 'Mono'];

// A family the app has a file for renders in itself; anything else - the legacy
// values, or a family dropped from the manifest - falls back to the system face.
export function fontFamilyFor(name) {
  return FONT_ASSETS[name] ? name : undefined;
}
