// GENERATED by scripts/gen-stickers.mjs - do not edit.
// Appended to every sticker url, so a re-render reaches phones that cached the
// previous one.
export const STICKER_VERSION = '202608091445';
