// GENERATED by scripts/gen-transition-previews.mjs - do not edit.
// Appended to every preview url so a re-render actually reaches phones that
// already cached the previous one. Changes only on a full regeneration.
export const TRANSITION_PREVIEW_VERSION = '202608080843';
