#!/usr/bin/env python3
"""Check every inline <script> on the hand-written website: does it PARSE, and does it
reference any identifier nothing defines?

The app has `expo export` and eslint. The website has nothing: it is hand-written HTML
served straight by nginx, so a syntax error ships silently - and a script that does not
parse does not run AT ALL, which looks like a page that merely does nothing rather than a
page that is broken. Three pages were in that state when this was written
(connect-accounts, dashboard, edit-post-video), each from an edit that wrapped code in a
callback and left the braces unbalanced.

Run it after ANY website edit:

    python3 scripts/check-website-js.py            # defaults to /var/www/tonefy-ai
    python3 scripts/check-website-js.py <dir>

Exits non-zero if anything fails either check, so it can gate a commit.

The second check exists because the first is not enough: a page whose script parses
perfectly still throws on the first render if it calls a helper nobody wrote. That happened
twice in one afternoon here - `showToast`/`showConfirm`/`closeConfirm` were referenced by
markup and never defined, and a `LOGO` map was used by a renderer after the edit that was
meant to add it failed.

It runs eslint's own `no-undef` rather than a regex. A first attempt at matching
identifiers by hand reported five working pages as broken - `async` arrows and
destructuring from a dynamic import both defeat it - and a guard that cries wolf is a guard
nobody runs. eslint already knows what a binding is.
"""
import os
import re
import subprocess
import sys
import tempfile

SCRIPT_RE = re.compile(r'<script(?![^>]*\bsrc=)([^>]*)>([\s\S]*?)</script>', re.I)


def check(path):
    with open(path, encoding='utf-8') as fh:
        html = fh.read()
    problems = []
    for index, match in enumerate(SCRIPT_RE.finditer(html), start=1):
        body = match.group(2)
        if not body.strip():
            continue
        # .mjs so `import` at the top level parses; a classic script that happens to
        # contain no modules parses the same way, so one suffix covers both.
        tmp = tempfile.NamedTemporaryFile('w', suffix='.mjs', delete=False, encoding='utf-8')
        try:
            tmp.write(body)
            tmp.close()
            result = subprocess.run(['node', '--check', tmp.name],
                                    capture_output=True, text=True)
        finally:
            os.unlink(tmp.name)
        if result.returncode:
            line = next((l for l in result.stderr.splitlines() if 'Error' in l),
                        result.stderr.strip().splitlines()[0] if result.stderr.strip() else '?')
            problems.append(f'block {index}: {line.strip()}')
            continue          # an unparseable block cannot be analysed further
        problems.extend(f'block {index}: {u}' for u in undefined_names(body))
    return problems



REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCRATCH = os.path.join(REPO, '.webcheck')
ESLINT_CONFIG = """// generated by scripts/check-website-js.py
const browser = {};
for (const g of ("window document location navigator history console fetch setTimeout clearTimeout "
  + "setInterval clearInterval alert confirm prompt sessionStorage localStorage URLSearchParams URL "
  + "FormData Blob File FileReader Image Audio Date Math JSON Promise Symbol Intl AbortController "
  + "Event CustomEvent MutationObserver IntersectionObserver requestAnimationFrame cancelAnimationFrame "
  + "getComputedStyle btoa atob structuredClone crypto performance TextEncoder TextDecoder Headers "
  + "Request Response HTMLElement Node NodeList CSS screen frames self top parent").split(" ")) browser[g] = "readonly";
// Names the checked block puts on window itself, and globals from any <script src> tag.
for (const g of "__EXTRA__".split(" ").filter(Boolean)) browser[g] = "writable";
export default [{
  files: ["**/*.mjs"],
  languageOptions: { ecmaVersion: 2022, sourceType: "module", globals: browser },
  rules: { "no-undef": "error" },
}];
"""


# Loaded by a <script src=...> the page includes rather than declared in the block itself.
EXTERNAL_GLOBALS = ['tailwind']


def undefined_names(body):
    """Names the script uses that nothing defines - eslint's no-undef, not a guess."""
    os.makedirs(SCRATCH, exist_ok=True)
    # `window.foo = ...` is how these pages expose a handler to an inline onclick, and it
    # really does create a global - window IS the global object - but it declares no
    # binding, so no-undef flags the bare call. Feed those names in as globals rather than
    # reporting working code.
    exposed = re.findall(r'\bwindow\.([A-Za-z_$][\w$]*)\s*=', body)
    cfg = os.path.join(SCRATCH, 'cfg.mjs')
    with open(cfg, 'w', encoding='utf-8') as fh:
        extra = ' '.join(sorted(set(exposed + EXTERNAL_GLOBALS)))
        fh.write(ESLINT_CONFIG.replace('__EXTRA__', extra))
    target = os.path.join(SCRATCH, 'block.mjs')
    with open(target, 'w', encoding='utf-8') as fh:
        fh.write(body)
    try:
        r = subprocess.run(['npx', 'eslint', '--no-config-lookup', '--config', cfg, target],
                           capture_output=True, text=True, cwd=REPO)
    except FileNotFoundError:
        return ['(eslint not available - parse check only)']
    out = []
    for line in r.stdout.splitlines():
        m = re.search(r"'([^']+)' is not defined", line)
        if m:
            out.append(f"uses '{m.group(1)}' but nothing defines it")
    return sorted(set(out))


def main():
    root = sys.argv[1] if len(sys.argv) > 1 else '/var/www/tonefy-ai'
    if not os.path.isdir(root):
        print(f'not a directory: {root}')
        return 2
    pages = sorted(f for f in os.listdir(root) if f.endswith('.html'))
    if not pages:
        print(f'no .html files in {root}')
        return 2
    broken = 0
    for page in pages:
        problems = check(os.path.join(root, page))
        if problems:
            broken += 1
            print(f'BROKEN  {page}')
            for problem in problems:
                print(f'          {problem}')
    print(f'\n{len(pages)} pages checked, {broken} broken.')
    return 1 if broken else 0


if __name__ == '__main__':
    sys.exit(main())
