#!/usr/bin/env python3
"""Downloads a set of illustrated avatars and writes the index that maps them in.

Run: python3 scripts/fetch-voice-avatars.py

Bundled rather than fetched on device on purpose. Loading 325 avatars from an API at
render time would put a network round trip in front of every voice card, and would make
the picker depend on a third-party service staying up. These are ~8KB each.

Style is `notionists` - the same restrained illustrated portrait Notion uses - rather
than `avataaars`, which reads as a cartoon. Photorealistic faces were considered and
rejected: the free sources either forbid using identifiable people in ways implying
endorsement or have unclear provenance, and putting a real human face on a text-to-speech
engine implies a person performed it when nobody did. Other styles are a one-word change
here: personas, lorelei, micah, open-peeps, adventurer.

DiceBear is open source and free. Facial hair is forced off for the female set and made
likely for the male set, which is what makes the two read differently - the style has no
gender parameter of its own.
"""
import pathlib, urllib.request, sys

APP = pathlib.Path(__file__).resolve().parent.parent
OUT = APP / "assets" / "avatars"
OUT.mkdir(parents=True, exist_ok=True)

STYLE = "notionists"
BG = "b6e3f4,c0aede,d1d4f9,ffd5dc,ffdfbf,c9f2d0,ffe0b3"
N = 30

def fetch(kind, i):
    seed = f"{kind}{i}"
    extra = "facialHairProbability=0" if kind == "f" else "facialHairProbability=70"
    url = (f"https://api.dicebear.com/9.x/{STYLE}/png?seed={seed}&size=128"
           f"&backgroundColor={BG}&{extra}")
    dest = OUT / f"{kind}{i:02d}.png"
    if dest.exists() and dest.stat().st_size > 1000:
        return False
    urllib.request.urlretrieve(url, dest)
    return True

added = 0
for kind in ("f", "m"):
    for i in range(1, N + 1):
        try:
            if fetch(kind, i):
                added += 1
        except Exception as e:
            print(f"  {kind}{i}: {e}", file=sys.stderr)

rows = []
for kind in ("f", "m"):
    for i in range(1, N + 1):
        rows.append(f"  require('../assets/avatars/{kind}{i:02d}.png'),")
female = "\n".join(rows[:N])
male = "\n".join(rows[N:])

(APP / "constants" / "avatars.js").write_text(
    "// GENERATED by scripts/fetch-voice-avatars.py - do not edit by hand.\n"
    "//\n"
    "// Metro needs every asset path to be a literal require, so this file exists rather\n"
    "// than a loop over filenames. Two sets, because a male voice wearing a female face\n"
    "// reads as a bug rather than as a stylistic choice.\n\n"
    "export const FEMALE_AVATARS = [\n" + female + "\n];\n\n"
    "export const MALE_AVATARS = [\n" + male + "\n];\n\n"
    "// Deterministic per voice, so a voice keeps its face between launches and between\n"
    "// screens. Hashing the id rather than using list position means inserting a voice\n"
    "// does not reshuffle everyone else's.\n"
    "export function avatarFor(voice) {\n"
    "  const set = voice?.gender === 'Male' ? MALE_AVATARS : FEMALE_AVATARS;\n"
    "  const id = String(voice?.id || '');\n"
    "  let h = 0;\n"
    "  for (let i = 0; i < id.length; i += 1) h = (h * 31 + id.charCodeAt(i)) >>> 0;\n"
    "  return set[h % set.length];\n"
    "}\n",
    encoding="utf-8")
print(f"avatars downloaded: {added} new, {len(list(OUT.glob('*.png')))} total")
