#!/usr/bin/env python3
"""Regenerates the voice catalogue from edge-tts's own voice list.

Run:  python3 scripts/generate-voices.py
Writes: constants/voices.js  (app)  and  ~/Tonefy-react/backend/voices.json (backend)

edge-tts is Microsoft Edge's read-aloud service. It is free, needs no key, and is
already installed and used by /api/generate-audio. Asking it for the list rather than
hand-writing one is the whole point: a name typed from memory that does not exist fails
at generation time, in front of the user.
"""
import asyncio, json, re, sys, pathlib

APP = pathlib.Path(__file__).resolve().parent.parent
BACKEND = pathlib.Path.home() / "Tonefy-react" / "backend"

# gTTS voices stay: they are the free tier, and they are a different engine.
GTTS = [
    {"id": "gtts-us", "engine": "gtts", "tld": "com",    "label": "Sarah", "accent": "US Female",
     "locale": "en-US", "country": "US", "gender": "Female", "lang": "en", "free": True},
    {"id": "gtts-uk", "engine": "gtts", "tld": "co.uk",  "label": "Emma",  "accent": "UK Female",
     "locale": "en-GB", "country": "GB", "gender": "Female", "lang": "en", "free": True},
    {"id": "gtts-au", "engine": "gtts", "tld": "com.au", "label": "Olivia","accent": "AU Female",
     "locale": "en-AU", "country": "AU", "gender": "Female", "lang": "en", "free": True},
]

# Two edge voices are free as well, so a free account has a male option and something
# that is not gTTS's flat delivery. Everything else is Pro/Creator.
FREE_EDGE = {"en-US-AvaNeural", "en-US-AndrewNeural"}

LANG_NAMES = {
 "af":"Afrikaans","am":"Amharic","ar":"Arabic","az":"Azerbaijani","bg":"Bulgarian",
 "bn":"Bengali","bs":"Bosnian","ca":"Catalan","cs":"Czech","cy":"Welsh","da":"Danish",
 "de":"German","el":"Greek","en":"English","es":"Spanish","et":"Estonian","fa":"Persian",
 "fi":"Finnish","fil":"Filipino","fr":"French","ga":"Irish","gl":"Galician","gu":"Gujarati",
 "he":"Hebrew","hi":"Hindi","hr":"Croatian","hu":"Hungarian","id":"Indonesian",
 "is":"Icelandic","it":"Italian","iu":"Inuktitut","ja":"Japanese","jv":"Javanese",
 "ka":"Georgian","kk":"Kazakh","km":"Khmer","kn":"Kannada","ko":"Korean","lo":"Lao",
 "lt":"Lithuanian","lv":"Latvian","mk":"Macedonian","ml":"Malayalam","mn":"Mongolian",
 "mr":"Marathi","ms":"Malay","mt":"Maltese","my":"Burmese","nb":"Norwegian","ne":"Nepali",
 "nl":"Dutch","pl":"Polish","ps":"Pashto","pt":"Portuguese","ro":"Romanian","ru":"Russian",
 "si":"Sinhala","sk":"Slovak","sl":"Slovenian","so":"Somali","sq":"Albanian","sr":"Serbian",
 "su":"Sundanese","sv":"Swedish","sw":"Swahili","ta":"Tamil","te":"Telugu","th":"Thai",
 "tr":"Turkish","uk":"Ukrainian","ur":"Urdu","uz":"Uzbek","vi":"Vietnamese",
 "zh":"Chinese","zu":"Zulu",
}

def display_name(short_name):
    # "en-US-AvaNeural" -> "Ava"
    m = re.match(r"^[a-z]{2,3}-[A-Za-z0-9]+-(.+?)(Neural|Multilingual.*)?$", short_name)
    return m.group(1) if m else short_name

async def main():
    import edge_tts
    voices = await edge_tts.list_voices()
    out = list(GTTS)
    seen = {v["id"] for v in out}

    for v in sorted(voices, key=lambda x: (x["Locale"], x["ShortName"])):
        short = v["ShortName"]
        locale = v["Locale"]
        country = locale.split("-")[1][:2].upper() if "-" in locale else "US"
        lang_tag = locale.split("-")[0]
        name = display_name(short)
        vid = "edge-" + short
        if vid in seen:
            continue
        seen.add(vid)
        out.append({
            "id": vid,
            "engine": "edge",
            "name": short,
            "label": name,
            "accent": f'{country} {v["Gender"]}',
            "locale": locale,
            "country": country,
            "gender": v["Gender"],
            "lang": lang_tag,
            "free": short in FREE_EDGE,
        })

    # --- app catalogue -------------------------------------------------------
    app_rows = []
    for v in out:
        app_rows.append("  " + json.dumps({
            "id": v["id"], "label": v["label"], "accent": v["accent"],
            "country": v["country"], "locale": v["locale"], "lang": v["lang"],
            "langName": LANG_NAMES.get(v["lang"], v["lang"].upper()),
            "gender": v["gender"], "free": v["free"],
        }, ensure_ascii=False) + ",")
    header = (
        "// GENERATED by scripts/generate-voices.py - do not edit by hand.\n"
        "//\n"
        "// Read out of edge-tts's own list_voices() rather than typed: a voice name that\n"
        "// does not exist fails at generation time, in front of the user. Ids must match\n"
        "// voices.json in ~/Tonefy-react/backend, which is generated by the same script.\n"
        "//\n"
        f"// {len(out)} voices across {len(set(v['lang'] for v in out))} languages.\n\n"
    )
    (APP / "constants" / "voices.js").write_text(
        header + "export const VOICES = [\n" + "\n".join(app_rows) + "\n];\n\n"
        "export function voiceById(id) {\n"
        "  return VOICES.find(v => v.id === id) || VOICES[0];\n"
        "}\n\n"
        "export const FREE_VOICE_IDS = VOICES.filter(v => v.free).map(v => v.id);\n",
        encoding="utf-8")

    # --- backend catalogue ---------------------------------------------------
    backend = {}
    for v in out:
        if v["engine"] == "gtts":
            backend[v["id"]] = {"engine": "gtts", "tld": v["tld"], "label": v["label"], "free": v["free"]}
        else:
            backend[v["id"]] = {"engine": "edge", "name": v["name"], "label": v["label"], "free": v["free"]}
    (BACKEND / "voices.json").write_text(json.dumps(backend, ensure_ascii=False, indent=1), encoding="utf-8")

    print(f"voices: {len(out)}  free: {sum(1 for v in out if v['free'])}  languages: {len(set(v['lang'] for v in out))}")

asyncio.run(main())
